version: "3.7"

services:
  app:
    build:
      args:
        user: laravel
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    # image: laravel
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./app:/var/www
    networks:
      - laravel-net

  db:
    image: mysql:5.7
    container_name: laravel-mysql
    restart: unless-stopped
    ports:
      - 3306:3306 
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./config/mysql:/docker-entrypoint-initdb.d
    networks:
      - laravel-net

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./app:/var/www
      - ./config/nginx:/etc/nginx/conf.d/
    networks:
      - laravel-net

networks:
  laravel-net:
    driver: bridge